version: "3.9"

services: 
  database:
    image: postgres
    container_name: database_test
    restart: always
    ports: 
      - 5432:5432
    environment: 
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=test
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: test
    restart: always
    ports:
      - 3000:3000
      - 9229:9229
    volumes: 
      - .:/usr/app
    links: 
      - database
    depends_on: 
      - database


volumes: 
  pgdata:
    driver: local
